language: node_js
branches:
  only:
  - master
node_js:
  - '8'
addons:
  ssh_known_hosts: ssh.ivankristianto.com
script:
- echo 'Deploy!!'
before_deploy:
- openssl aes-256-cbc -K $encrypted_526abde80c1d_key -iv $encrypted_526abde80c1d_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ $ssh_username@$ssh_host:$full_path
  on:
    branch: master